#!/bin/bash
set -e

# Define target package workspace
TARGET_DIR="change-splash"
CONTROL_FILE="$TARGET_DIR/DEBIAN/control"

# 1. Ensure the DEBIAN structure exists
mkdir -p "$TARGET_DIR/DEBIAN"

# 2. Gather environment metadata dynamically from the current user context
CURRENT_USER=$(logname 2>/dev/null || echo $USER)
HOST_NAME=$(hostname)
SYSTEM_ARCH=$(dpkg --print-architecture)

# 3. Write a compliant control file with a trailing empty newline
cat << EOF > "$CONTROL_FILE"
Package: change-splash
Version: 1.0-1
Section: admin
Priority: optional
Architecture: $SYSTEM_ARCH
#Depends: plymouth, Grub, grub-pc | grub-efi
Maintainer: $CURRENT_USER <$CURRENT_USER@$HOST_NAME.local>
Description: Installs and sets a customer splash image the Grub bootloader.
 Generated by user $CURRENT_USER on a $SYSTEM_ARCH host system.
EOF

echo "✓ Successfully extracted user metadata and built: $CONTROL_FILE"
echo "--------------------------------------------------------"
cat "$CONTROL_FILE"
echo "--------------------------------------------------------"
echo "Building package with proper root owner mapping..."
dpkg-deb --root-owner-group --build "$TARGET_DIR"
